import {
  Atom,
  Blocks,
  Boxes,
  BrainCircuit,
  Braces,
  CalendarDays,
  Cloud,
  Code2,
  Container,
  Database,
  Download,
  Github,
  Layers3,
  Linkedin,
  Mail,
  Network,
  Server,
  Share2,
  Smartphone,
  Sparkles,
  Triangle,
  Workflow,
  Zap,
} from "lucide-react";

export const skillIconMap = {
  atom: Atom,
  layers: Layers3,
  braces: Braces,
  sparkles: Sparkles,
  server: Server,
  boxes: Boxes,
  share: Share2,
  cloud: Cloud,
  triangle: Triangle,
  container: Container,
  workflow: Workflow,
  brain: BrainCircuit,
  network: Network,
  smartphone: Smartphone,
  database: Database,
  zap: Zap,
  code: Code2,
  blocks: Blocks,
};

export const socialIconMap = {
  github: Github,
  linkedin: Linkedin,
  email: Mail,
  resume: Download,
  calendar: CalendarDays,
};
