import type { ProfessionConfig, ProfessionKey } from "@/types/portfolio-engine";

export const professionConfigs: ProfessionConfig[] = [
  {
    key: "software-technology",
    label: "Software & Technology",
    description:
      "Engineering portfolios for frontend, backend, full-stack, mobile, DevOps, and QA.",
    suggestedSections: [
      "About",
      "Technical Skills",
      "Projects",
      "Case Studies",
      "Experience",
      "Contact",
    ],
    suggestedSkills: ["TypeScript", "React", "APIs", "Testing", "Cloud", "System Design"],
    projectStructure: [
      "Problem",
      "Role",
      "Architecture",
      "Tradeoffs",
      "Result",
      "Code or demo",
    ],
    onboardingQuestions: [
      "What systems or products have you shipped?",
      "Which stack do you want to be known for?",
      "What measurable impact can you show?",
    ],
    aiPromptConfig: {
      roleContext: "software and technology professional",
      tone: "clear, technical, outcome-oriented",
      focus: ["systems", "reliability", "delivery", "impact"],
    },
    scoringRules: [
      "technical proof",
      "case-study clarity",
      "measurable outcomes",
      "contact readiness",
    ],
    recommendedTemplates: ["signal", "stage"],
  },
  {
    key: "data-ai",
    label: "Data & AI",
    description:
      "Portfolios for data analysts, AI builders, ML engineers, BI, and analytics teams.",
    suggestedSections: [
      "About",
      "Data Skills",
      "Projects",
      "Dashboards",
      "Model or Analysis Notes",
      "Contact",
    ],
    suggestedSkills: ["SQL", "Python", "Dashboards", "Pipelines", "Evaluation", "Storytelling"],
    projectStructure: ["Question", "Dataset", "Method", "Insight", "Decision", "Limitations"],
    onboardingQuestions: [
      "What kind of data work do you want to attract?",
      "Which tools do you use most confidently?",
      "What decisions did your analysis improve?",
    ],
    aiPromptConfig: {
      roleContext: "data and AI professional",
      tone: "analytical, precise, evidence-led",
      focus: ["data quality", "insight", "evaluation", "business value"],
    },
    scoringRules: ["data context", "method clarity", "insight quality", "responsible AI notes"],
    recommendedTemplates: ["signal", "ledger"],
  },
  {
    key: "product",
    label: "Product",
    description: "Outcome-led portfolios for PMs, product owners, and product strategists.",
    suggestedSections: [
      "About",
      "Product Wins",
      "Case Studies",
      "Roadmaps",
      "Experiments",
      "Contact",
    ],
    suggestedSkills: [
      "Discovery",
      "Prioritization",
      "Roadmapping",
      "Analytics",
      "Experimentation",
    ],
    projectStructure: [
      "Customer problem",
      "Strategy",
      "Tradeoffs",
      "Launch",
      "Metrics",
      "Learning",
    ],
    onboardingQuestions: [
      "Which user or business problem did you own?",
      "What tradeoff did you make?",
      "What changed after launch?",
    ],
    aiPromptConfig: {
      roleContext: "product professional",
      tone: "strategic, concise, commercially aware",
      focus: ["customer insight", "prioritization", "metrics", "launch quality"],
    },
    scoringRules: ["customer clarity", "metrics", "strategic tradeoffs", "launch evidence"],
    recommendedTemplates: ["stage", "ledger"],
  },
  {
    key: "design",
    label: "Design",
    description: "Visual, product, brand, UX, and interaction design portfolios.",
    suggestedSections: [
      "About",
      "Selected Work",
      "Process",
      "Before and After",
      "Services",
      "Contact",
    ],
    suggestedSkills: ["UX", "UI", "Research", "Brand", "Prototyping", "Design Systems"],
    projectStructure: [
      "Brief",
      "Constraints",
      "Exploration",
      "Final direction",
      "Outcome",
      "Reflection",
    ],
    onboardingQuestions: [
      "What kind of design work should visitors remember?",
      "Which process artifacts can you show?",
      "What business or user outcome did the work support?",
    ],
    aiPromptConfig: {
      roleContext: "design professional",
      tone: "visual, thoughtful, human-centered",
      focus: ["taste", "process", "constraints", "outcomes"],
    },
    scoringRules: ["visual proof", "process clarity", "outcome framing", "accessibility"],
    recommendedTemplates: ["atelier", "stage"],
  },
  {
    key: "marketing",
    label: "Marketing",
    description:
      "Growth, content, social, brand, lifecycle, and performance marketing portfolios.",
    suggestedSections: ["About", "Campaigns", "Results", "Channels", "Playbooks", "Contact"],
    suggestedSkills: ["Campaigns", "SEO", "Paid Media", "Content", "Lifecycle", "Analytics"],
    projectStructure: [
      "Audience",
      "Campaign goal",
      "Channels",
      "Execution",
      "Results",
      "Learning",
    ],
    onboardingQuestions: [
      "What channels do you want to be hired for?",
      "Which campaign has the strongest numbers?",
      "What audience do you understand deeply?",
    ],
    aiPromptConfig: {
      roleContext: "marketing professional",
      tone: "clear, energetic, metric-aware",
      focus: ["audience", "campaign strategy", "conversion", "growth"],
    },
    scoringRules: ["audience clarity", "campaign metrics", "channel fit", "proof of execution"],
    recommendedTemplates: ["stage", "atelier"],
  },
  {
    key: "writing",
    label: "Writing",
    description:
      "Portfolios for copywriters, technical writers, editors, journalists, and content strategists.",
    suggestedSections: [
      "About",
      "Writing Samples",
      "Topics",
      "Clients",
      "Editorial Process",
      "Contact",
    ],
    suggestedSkills: [
      "Copywriting",
      "Editing",
      "Research",
      "SEO",
      "Technical Writing",
      "Storytelling",
    ],
    projectStructure: ["Brief", "Audience", "Draft challenge", "Final piece", "Impact", "Link"],
    onboardingQuestions: [
      "What topics should define your writing brand?",
      "Which samples prove range?",
      "Who is your ideal reader or client?",
    ],
    aiPromptConfig: {
      roleContext: "writing professional",
      tone: "sharp, editorial, credible",
      focus: ["voice", "audience", "clarity", "published proof"],
    },
    scoringRules: ["sample quality", "niche clarity", "proof links", "editorial positioning"],
    recommendedTemplates: ["atelier", "ledger"],
  },
  {
    key: "photography-video",
    label: "Photography & Video",
    description:
      "Image-led portfolios for photographers, filmmakers, editors, and visual storytellers.",
    suggestedSections: [
      "About",
      "Portfolio",
      "Featured Shoots",
      "Services",
      "Client Proof",
      "Contact",
    ],
    suggestedSkills: [
      "Photography",
      "Video",
      "Editing",
      "Lighting",
      "Directing",
      "Post-production",
    ],
    projectStructure: [
      "Client or theme",
      "Creative direction",
      "Production",
      "Final assets",
      "Reach",
      "Gallery",
    ],
    onboardingQuestions: [
      "What visual style should clients associate with you?",
      "Which shoots best prove range?",
      "What services do you want to sell?",
    ],
    aiPromptConfig: {
      roleContext: "photography and video professional",
      tone: "visual, confident, client-ready",
      focus: ["style", "production quality", "client outcomes", "booking"],
    },
    scoringRules: ["visual strength", "service clarity", "client proof", "booking readiness"],
    recommendedTemplates: ["atelier", "stage"],
  },
  {
    key: "architecture-engineering",
    label: "Architecture & Engineering",
    description:
      "Built-environment, civil, mechanical, electrical, and design engineering portfolios.",
    suggestedSections: [
      "About",
      "Projects",
      "Drawings",
      "Methods",
      "Certifications",
      "Contact",
    ],
    suggestedSkills: [
      "Design",
      "CAD",
      "Project Delivery",
      "Compliance",
      "Site Coordination",
      "Documentation",
    ],
    projectStructure: [
      "Scope",
      "Constraints",
      "Method",
      "Deliverables",
      "Safety or compliance",
      "Result",
    ],
    onboardingQuestions: [
      "What project scale do you want to be trusted with?",
      "Which technical standards matter in your field?",
      "What drawings, photos, or results can you show?",
    ],
    aiPromptConfig: {
      roleContext: "architecture and engineering professional",
      tone: "precise, practical, technically credible",
      focus: ["constraints", "delivery", "safety", "documentation"],
    },
    scoringRules: ["project detail", "technical proof", "compliance", "delivery outcomes"],
    recommendedTemplates: ["ledger", "signal"],
  },
  {
    key: "business-consulting",
    label: "Business & Consulting",
    description:
      "Trust-forward portfolios for consultants, operators, strategists, and advisors.",
    suggestedSections: [
      "About",
      "Services",
      "Case Studies",
      "Frameworks",
      "Client Outcomes",
      "Contact",
    ],
    suggestedSkills: [
      "Strategy",
      "Operations",
      "Research",
      "Change Management",
      "Analysis",
      "Facilitation",
    ],
    projectStructure: [
      "Client problem",
      "Diagnosis",
      "Recommendation",
      "Implementation",
      "Outcome",
      "Next steps",
    ],
    onboardingQuestions: [
      "What client problem do you solve best?",
      "Which outcomes can you quantify?",
      "What framework or operating model do you bring?",
    ],
    aiPromptConfig: {
      roleContext: "business and consulting professional",
      tone: "executive, credible, outcome-led",
      focus: ["client value", "diagnosis", "recommendations", "results"],
    },
    scoringRules: ["service clarity", "case-study proof", "outcome metrics", "trust signals"],
    recommendedTemplates: ["ledger", "stage"],
  },
  {
    key: "finance",
    label: "Finance",
    description:
      "Portfolios for analysts, accountants, investment professionals, and finance operators.",
    suggestedSections: [
      "About",
      "Expertise",
      "Analysis",
      "Credentials",
      "Case Studies",
      "Contact",
    ],
    suggestedSkills: [
      "Financial Modeling",
      "Reporting",
      "Risk",
      "Excel",
      "Valuation",
      "Compliance",
    ],
    projectStructure: [
      "Objective",
      "Financial context",
      "Model or analysis",
      "Recommendation",
      "Controls",
      "Impact",
    ],
    onboardingQuestions: [
      "Which finance problems do you solve?",
      "What tools or credentials matter most?",
      "What numbers can you safely share?",
    ],
    aiPromptConfig: {
      roleContext: "finance professional",
      tone: "trustworthy, precise, compliance-aware",
      focus: ["analysis", "risk", "controls", "financial impact"],
    },
    scoringRules: ["trust", "quant proof", "compliance awareness", "clear expertise"],
    recommendedTemplates: ["ledger", "signal"],
  },
  {
    key: "research-academia",
    label: "Research & Academia",
    description: "Academic, lab, policy, and research portfolios.",
    suggestedSections: [
      "About",
      "Research Areas",
      "Publications",
      "Projects",
      "Teaching",
      "Contact",
    ],
    suggestedSkills: ["Research", "Writing", "Methods", "Teaching", "Data Analysis", "Grants"],
    projectStructure: [
      "Research question",
      "Method",
      "Contribution",
      "Publication",
      "Collaborators",
      "Next work",
    ],
    onboardingQuestions: [
      "What research theme should visitors remember?",
      "Which publications or outputs matter most?",
      "What collaboration or role are you seeking?",
    ],
    aiPromptConfig: {
      roleContext: "research and academia professional",
      tone: "scholarly, clear, accessible",
      focus: ["research contribution", "methods", "publications", "collaboration"],
    },
    scoringRules: [
      "research clarity",
      "publication proof",
      "method transparency",
      "contact purpose",
    ],
    recommendedTemplates: ["ledger", "atelier"],
  },
  {
    key: "students-graduates",
    label: "Students & Graduates",
    description:
      "Early-career portfolios for internships, graduate roles, scholarships, and first jobs.",
    suggestedSections: ["About", "Education", "Projects", "Skills", "Activities", "Contact"],
    suggestedSkills: [
      "Communication",
      "Research",
      "Tools",
      "Coursework",
      "Projects",
      "Teamwork",
    ],
    projectStructure: [
      "Goal",
      "What I built or did",
      "Skills used",
      "What I learned",
      "Result",
      "Next step",
    ],
    onboardingQuestions: [
      "What role, internship, or program are you targeting?",
      "Which school or personal project shows your potential?",
      "What are you learning now?",
    ],
    aiPromptConfig: {
      roleContext: "student or recent graduate",
      tone: "confident, honest, growth-oriented",
      focus: ["potential", "projects", "learning", "career direction"],
    },
    scoringRules: ["clear target", "project proof", "skills", "contact readiness"],
    recommendedTemplates: ["signal", "stage"],
  },
  {
    key: "freelancers",
    label: "Freelancers",
    description:
      "Client-winning portfolios for independent professionals and service providers.",
    suggestedSections: ["About", "Services", "Work", "Process", "Testimonials", "Contact"],
    suggestedSkills: [
      "Client Management",
      "Delivery",
      "Communication",
      "Pricing",
      "Operations",
    ],
    projectStructure: [
      "Client need",
      "Service delivered",
      "Timeline",
      "Outcome",
      "Testimonial",
      "Call to action",
    ],
    onboardingQuestions: [
      "What service should clients hire you for?",
      "Who is your ideal client?",
      "What proof makes you easy to trust?",
    ],
    aiPromptConfig: {
      roleContext: "freelance professional",
      tone: "client-ready, direct, trustworthy",
      focus: ["services", "outcomes", "trust", "conversion"],
    },
    scoringRules: ["service clarity", "client proof", "conversion path", "process"],
    recommendedTemplates: ["stage", "atelier"],
  },
  {
    key: "creative-arts",
    label: "Creative Arts",
    description:
      "Portfolios for artists, performers, makers, illustrators, and multidisciplinary creatives.",
    suggestedSections: ["About", "Works", "Exhibitions", "Process", "Press", "Contact"],
    suggestedSkills: [
      "Creative Direction",
      "Production",
      "Performance",
      "Exhibition",
      "Collaboration",
    ],
    projectStructure: [
      "Concept",
      "Medium",
      "Process",
      "Presentation",
      "Reception",
      "Availability",
    ],
    onboardingQuestions: [
      "What creative identity should the portfolio express?",
      "Which works should lead?",
      "What bookings, commissions, or opportunities do you want?",
    ],
    aiPromptConfig: {
      roleContext: "creative arts professional",
      tone: "expressive, polished, opportunity-aware",
      focus: ["body of work", "voice", "proof", "availability"],
    },
    scoringRules: ["work quality", "creative positioning", "proof", "opportunity clarity"],
    recommendedTemplates: ["atelier", "stage"],
  },
  {
    key: "events-hospitality",
    label: "Events & Hospitality",
    description:
      "Experience-led portfolios for event planners, hospitality teams, venues, and operators.",
    suggestedSections: [
      "About",
      "Events",
      "Services",
      "Operations",
      "Guest Outcomes",
      "Contact",
    ],
    suggestedSkills: [
      "Planning",
      "Vendor Management",
      "Guest Experience",
      "Operations",
      "Budgeting",
    ],
    projectStructure: [
      "Event goal",
      "Planning",
      "Execution",
      "Guest experience",
      "Outcome",
      "Gallery",
    ],
    onboardingQuestions: [
      "What type of events or hospitality work should you attract?",
      "Which guest outcomes matter most?",
      "What photos, testimonials, or numbers can you share?",
    ],
    aiPromptConfig: {
      roleContext: "events and hospitality professional",
      tone: "warm, organized, premium",
      focus: ["experience", "operations", "trust", "booking"],
    },
    scoringRules: ["service clarity", "visual proof", "guest outcomes", "booking readiness"],
    recommendedTemplates: ["stage", "atelier"],
  },
  {
    key: "education",
    label: "Education",
    description:
      "Portfolios for teachers, trainers, curriculum designers, tutors, and education operators.",
    suggestedSections: [
      "About",
      "Teaching Practice",
      "Curriculum",
      "Learner Outcomes",
      "Resources",
      "Contact",
    ],
    suggestedSkills: [
      "Teaching",
      "Curriculum",
      "Assessment",
      "Facilitation",
      "Learning Design",
    ],
    projectStructure: [
      "Learner need",
      "Approach",
      "Materials",
      "Assessment",
      "Outcome",
      "Reflection",
    ],
    onboardingQuestions: [
      "Who do you teach or support?",
      "What learning outcomes can you show?",
      "Which materials or methods prove your approach?",
    ],
    aiPromptConfig: {
      roleContext: "education professional",
      tone: "clear, supportive, evidence-aware",
      focus: ["learners", "methods", "outcomes", "resources"],
    },
    scoringRules: ["learner clarity", "outcome proof", "method", "resource quality"],
    recommendedTemplates: ["ledger", "stage"],
  },
  {
    key: "sales",
    label: "Sales",
    description:
      "Revenue portfolios for account executives, SDRs, partnerships, and sales leaders.",
    suggestedSections: ["About", "Wins", "Sales Motion", "Accounts", "Metrics", "Contact"],
    suggestedSkills: [
      "Prospecting",
      "Discovery",
      "Negotiation",
      "CRM",
      "Pipeline",
      "Partnerships",
    ],
    projectStructure: [
      "Market",
      "Sales challenge",
      "Motion",
      "Objections",
      "Result",
      "Learning",
    ],
    onboardingQuestions: [
      "What sales motion do you know best?",
      "What quota, revenue, or pipeline proof can you share?",
      "Which industries or buyer types do you understand?",
    ],
    aiPromptConfig: {
      roleContext: "sales professional",
      tone: "confident, concise, numbers-led",
      focus: ["pipeline", "revenue", "buyers", "process"],
    },
    scoringRules: ["revenue proof", "buyer clarity", "process", "contact path"],
    recommendedTemplates: ["stage", "ledger"],
  },
  {
    key: "hr-recruitment",
    label: "HR & Recruitment",
    description:
      "People portfolios for recruiters, HR business partners, L&D, and people operations.",
    suggestedSections: [
      "About",
      "People Programs",
      "Hiring Wins",
      "Process",
      "Culture Work",
      "Contact",
    ],
    suggestedSkills: [
      "Recruiting",
      "Employee Relations",
      "L&D",
      "People Ops",
      "Compliance",
      "Sourcing",
    ],
    projectStructure: [
      "People problem",
      "Stakeholders",
      "Process",
      "Controls",
      "Outcome",
      "Learning",
    ],
    onboardingQuestions: [
      "What people problem do you solve best?",
      "What hiring or HR outcomes can you show?",
      "Which industries or roles do you understand?",
    ],
    aiPromptConfig: {
      roleContext: "HR and recruitment professional",
      tone: "human, structured, trust-building",
      focus: ["people outcomes", "process", "compliance", "culture"],
    },
    scoringRules: ["people outcomes", "process quality", "trust", "role clarity"],
    recommendedTemplates: ["ledger", "stage"],
  },
  {
    key: "public-relations",
    label: "Public Relations",
    description: "Reputation portfolios for PR, comms, media relations, and corporate affairs.",
    suggestedSections: [
      "About",
      "Campaigns",
      "Media Wins",
      "Messaging",
      "Crisis Work",
      "Contact",
    ],
    suggestedSkills: [
      "Media Relations",
      "Messaging",
      "Crisis Comms",
      "Stakeholders",
      "Writing",
    ],
    projectStructure: [
      "Reputation goal",
      "Audience",
      "Message",
      "Channels",
      "Coverage",
      "Outcome",
    ],
    onboardingQuestions: [
      "What reputation problem do you help solve?",
      "What coverage or stakeholder proof can you show?",
      "Which sectors do you understand?",
    ],
    aiPromptConfig: {
      roleContext: "public relations professional",
      tone: "credible, concise, reputation-aware",
      focus: ["messaging", "coverage", "stakeholders", "outcomes"],
    },
    scoringRules: ["message clarity", "media proof", "stakeholder context", "outcomes"],
    recommendedTemplates: ["stage", "ledger"],
  },
  {
    key: "legal",
    label: "Legal",
    description:
      "Credibility-focused portfolios for lawyers, legal operations, compliance, and policy professionals.",
    suggestedSections: [
      "About",
      "Practice Areas",
      "Experience",
      "Publications",
      "Credentials",
      "Contact",
    ],
    suggestedSkills: [
      "Research",
      "Drafting",
      "Compliance",
      "Negotiation",
      "Advisory",
      "Policy",
    ],
    projectStructure: [
      "Issue",
      "Context",
      "Approach",
      "Risk",
      "Resolution",
      "Confidentiality note",
    ],
    onboardingQuestions: [
      "What legal or compliance area should define your profile?",
      "What work can you describe without breaching confidentiality?",
      "Which credentials matter most?",
    ],
    aiPromptConfig: {
      roleContext: "legal professional",
      tone: "precise, confidential, authoritative",
      focus: ["practice area", "risk", "advisory value", "credentials"],
    },
    scoringRules: ["confidentiality", "practice clarity", "credentials", "trust"],
    recommendedTemplates: ["ledger", "signal"],
  },
  {
    key: "healthcare",
    label: "Healthcare",
    description:
      "Trust-centered portfolios for clinicians, health operators, public health, and care professionals.",
    suggestedSections: [
      "About",
      "Practice",
      "Experience",
      "Programs",
      "Credentials",
      "Contact",
    ],
    suggestedSkills: [
      "Patient Care",
      "Operations",
      "Research",
      "Public Health",
      "Compliance",
      "Training",
    ],
    projectStructure: [
      "Health need",
      "Population",
      "Intervention",
      "Safety",
      "Outcome",
      "Ethics note",
    ],
    onboardingQuestions: [
      "Who do you serve in healthcare?",
      "What programs, research, or care outcomes can you share?",
      "Which credentials must be visible?",
    ],
    aiPromptConfig: {
      roleContext: "healthcare professional",
      tone: "careful, trustworthy, evidence-aware",
      focus: ["patients", "outcomes", "ethics", "credentials"],
    },
    scoringRules: ["trust", "credential clarity", "outcomes", "ethical framing"],
    recommendedTemplates: ["ledger", "stage"],
  },
  {
    key: "entrepreneurs",
    label: "Entrepreneurs",
    description:
      "Founder portfolios for operators, builders, creators, and small business owners.",
    suggestedSections: [
      "About",
      "Ventures",
      "Products",
      "Traction",
      "Operating Principles",
      "Contact",
    ],
    suggestedSkills: ["Strategy", "Sales", "Product", "Operations", "Leadership", "Finance"],
    projectStructure: [
      "Opportunity",
      "Customer",
      "Product",
      "Traction",
      "Business model",
      "Next milestone",
    ],
    onboardingQuestions: [
      "What venture or offer should visitors care about first?",
      "What traction or proof can you share?",
      "What opportunity are you looking for?",
    ],
    aiPromptConfig: {
      roleContext: "entrepreneur or founder",
      tone: "clear, ambitious, commercially grounded",
      focus: ["customer", "traction", "offer", "next milestone"],
    },
    scoringRules: ["offer clarity", "traction", "customer proof", "conversion path"],
    recommendedTemplates: ["stage", "signal"],
  },
];

export function getProfessionConfig(key: ProfessionKey) {
  return professionConfigs.find((profession) => profession.key === key) ?? professionConfigs[0];
}

export function isProfessionKey(value: string): value is ProfessionKey {
  return professionConfigs.some((profession) => profession.key === value);
}
