import type { PortfolioTemplate } from "@/types/portfolio-engine";

export const portfolioTemplates: PortfolioTemplate[] = [
  {
    id: "signal",
    name: "Signal",
    description: "A sharp technical profile for engineers, data people, and operators.",
    bestFor: ["Software & Technology", "Data & AI", "SRE", "Cybersecurity"],
    accentClass: "from-mint/30 via-cobalt/20 to-transparent",
    previewClass: "border-primary/50 bg-primary/10",
    tier: "free",
    category: "core",
    creatorName: "Portfolio Engine",
    usageCount: 1280,
  },
  {
    id: "atelier",
    name: "Atelier",
    description: "Editorial layout for designers, writers, photographers, and creatives.",
    bestFor: ["Design", "Writing", "Photography & Video", "Creative Arts"],
    accentClass: "from-rose/30 via-ember/20 to-transparent",
    previewClass: "border-rose/50 bg-rose/10",
    tier: "free",
    category: "core",
    creatorName: "Portfolio Engine",
    supportsVideo: true,
    usageCount: 920,
  },
  {
    id: "ledger",
    name: "Ledger",
    description: "Trust-forward format for business, finance, legal, and consulting work.",
    bestFor: ["Business & Consulting", "Finance", "Legal", "Healthcare"],
    accentClass: "from-cobalt/25 via-mint/20 to-transparent",
    previewClass: "border-cobalt/50 bg-cobalt/10",
    tier: "free",
    category: "core",
    creatorName: "Portfolio Engine",
    usageCount: 740,
  },
  {
    id: "stage",
    name: "Stage",
    description: "Outcome-led presentation for PMs, marketers, sales, events, and founders.",
    bestFor: ["Product", "Marketing", "Sales", "Events & Hospitality", "Entrepreneurs"],
    accentClass: "from-ember/30 via-primary/20 to-transparent",
    previewClass: "border-secondary/60 bg-secondary/10",
    tier: "free",
    category: "core",
    creatorName: "Portfolio Engine",
    supportsVideo: true,
    usageCount: 1060,
  },
  {
    id: "operator",
    name: "Operator",
    description: "A dense execution dashboard for senior operators, founders, and consultants.",
    bestFor: ["Entrepreneurs", "Business & Consulting", "Product", "Sales"],
    accentClass: "from-cobalt/30 via-primary/20 to-transparent",
    previewClass: "border-accent/60 bg-accent/10",
    tier: "pro",
    category: "marketplace",
    creatorName: "Akingbade Studio",
    marketplaceBadge: "Agency favorite",
    priceUsd: 29,
    usageCount: 410,
  },
  {
    id: "gallery",
    name: "Gallery",
    description: "A visual-first template for video, photography, art direction, and launches.",
    bestFor: ["Photography & Video", "Creative Arts", "Design", "Events & Hospitality"],
    accentClass: "from-rose/35 via-accent/20 to-transparent",
    previewClass: "border-rose/60 bg-rose/10",
    tier: "pro",
    category: "marketplace",
    creatorName: "Akingbade Studio",
    marketplaceBadge: "Video ready",
    priceUsd: 39,
    supportsVideo: true,
    usageCount: 365,
  },
  {
    id: "pitch",
    name: "Pitch",
    description: "A conversion-focused layout for freelancers, sales leaders, and founders.",
    bestFor: ["Freelancers", "Sales", "Marketing", "Entrepreneurs"],
    accentClass: "from-ember/35 via-rose/20 to-transparent",
    previewClass: "border-secondary/60 bg-secondary/10",
    tier: "pro",
    category: "marketplace",
    creatorName: "Portfolio Engine",
    marketplaceBadge: "Lead capture",
    priceUsd: 19,
    usageCount: 590,
  },
  {
    id: "agency",
    name: "Agency",
    description: "A multi-person showcase for studios, collectives, and client delivery teams.",
    bestFor: ["Business & Consulting", "Design", "Marketing", "Public Relations"],
    accentClass: "from-mint/25 via-ember/20 to-transparent",
    previewClass: "border-primary/60 bg-primary/10",
    tier: "pro",
    category: "marketplace",
    creatorName: "Portfolio Engine",
    marketplaceBadge: "Team accounts",
    priceUsd: 49,
    supportsVideo: true,
    usageCount: 280,
  },
];

export function getTemplateById(templateId: string) {
  return (
    portfolioTemplates.find((template) => template.id === templateId) ?? portfolioTemplates[0]
  );
}
